catalog:
  '@ai-sdk/anthropic': ^3.0.58
  '@ai-sdk/google': ^3.0.43
  '@ai-sdk/openai': ^3.0.60
  '@ai-sdk/vue': ^3.0.116
  '@antfu/eslint-config': ^7.6.1
  '@faker-js/faker': ^10.3.0
  '@iconify-json/lucide': ^1.2.95
  '@iconify-json/simple-icons': ^1.2.72
  '@nuxt/content': ^3.12.0
  '@nuxt/image': ^2.0.0
  '@nuxt/test-utils': ^4.0.0
  '@nuxt/ui': ^4.5.1
  '@nuxtjs/i18n': ^10.3.0
  '@nuxtjs/seo': ^3.4.0
  '@octokit/rest': ^22.0.1
  '@pinia/colada': ^0.21.7
  '@pinia/colada-nuxt': ^0.3.2
  '@pinia/nuxt': ^0.11.3
  '@standard-schema/spec': ^1.1.0
  '@types/bcrypt': ^6.0.0
  '@types/nodemailer': ^7.0.11
  '@vue/test-utils': ^2.4.6
  '@vueuse/nuxt': ^14.2.1
  '@vueuse/router': ^14.2.1
  ai: ^6.0.116
  argon2: ^0.44.0
  bcrypt: ^6.0.0
  better-sqlite3: ^12.6.2
  date-fns: ^4.1.0
  dotenv: ^17.3.1
  dotenv-cli: ^11.0.0
  drizzle-kit: ^0.31.9
  drizzle-orm: ^0.45.1
  eslint: ^10.0.2
  happy-dom: ^20.8.3
  hookable: ^6.0.1
  liquidjs: ^10.24.0
  mitt: ^3.0.1
  nodemailer: ^8.0.1
  nuxt: ^4.3.1
  nuxt-mcp-dev: ^0.3.2
  nuxt-og-image: ^5.1.13
  pinia: ^3.0.4
  playwright-core: ^1.58.2
  postgres: ^3.4.8
  sharp: ^0.34.5
  tsx: ^4.21.0
  typescript: ^5.9.3
  ulid: ^3.0.2
  undici: ^7.22.0
  vitest: ^4.0.18
  vue-advanced-cropper: ^2.8.9
  vue-tsc: ^3.2.5
  zod: ^4.3.6

catalogMode: prefer

onlyBuiltDependencies:
  - '@parcel/watcher'
  - argon2
  - bcrypt
  - better-sqlite3
  - esbuild
  - sharp
  - vue-demi

shellEmulator: true
